### ISSUE TITLE
Enhancement: Names

### ISSUE THREAD

**Issue by matys18** [Zalodu/random#4]
Being able to assign a name to a number would be a nice feature. The data could be saved in cookies, to avoid re-entering the entire list every time. :thought_balloon:

**Comment by codewitchio** [comment]
@matys18 Originally I thought about not randomly selecting a number at all, but randomly selecting one of the github handles and providing a link to that person's assignment for the current week. However, that would require some way to enter exactly which students are present, instead of just how many. Any ideas? It would be awesome if it could somehow take the data from Mac's attendance Excel/Numbers sheet.

**Comment by codewitchio** [comment]
Or it could just be presented as two lists of all the people, one list for present people, and one list for absent ones where clicking them would just move them to the other list. That way it would be a very quick setup to select which students are present/absent. If it saves the list in cookies, all you would need to do for every övning would be to change who's present and who isn't.

**Comment by matys18** [comment]
Exactly, either two lists or a list of all names with checkboxes.

**Comment by codewitchio** [comment]
I think one list is better actually, since most people will be attending, only a few will be on the list for absent students. Great idea :+1:

**Comment by codewitchio** [comment]
Added in... one of the many commits in the [names](https://github.com/Zalodu/random/tree/names) branch.
